# Generated by Django 4.1.7 on 2023-03-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brand_image_category_image_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-createdAt',)},
        ),
    ]
